name: Build Windows Installer

on:
  workflow_dispatch:

jobs:
  build_installer:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download EXE artifact from Build EXE workflow
        uses: actions/download-artifact@v4
        with:
          name: WhatsApp-Sender-EXE
          path: dist

      - name: Install Inno Setup
        uses: juszczak/innosetup-action@v1

      - name: Build Installer
        run: |
          iscc installer.iss

      - name: Upload Installer
        uses: actions/upload-artifact@v4
        with:
          name: WhatsApp-Sender-Installer
          path: installer/WhatsAppBulkSender_Setup.exe